### ISSUE TITLE
Doesn't install in Sierra?

### ISSUE THREAD

**Issue by mattneub** [BrendanThompson/rb-scpt#17]
Here's what I did (Sierra 10.12.6):

    matt$ sudo gem install rb-scpt

Here's what happened:

```
Fetching: rb-scpt-1.0.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing rb-scpt:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20181203-4585-apfmmw.rb extconf.rb
create /Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3/src/osx_ruby.h ...
create /Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3/src/osx_intern.h ...
creating Makefile

current directory: /Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3
make "DESTDIR="
make: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0/universal-darwin16/ruby/config.h', needed by `SendThreadSafe.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/rb-scpt-1.0.3 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-16/2.3.0/rb-scpt-1.0.3/gem_make.out

```

**Comment by mattneub** [comment]
I should add, the results are different (though still not successful) if I change ruby versions via rbenv, so it would appear that the problem is some interaction between Ruby 2.3.0 and Xcode 9.2 (the last version that runs on Sierra, I believe).

**Comment by mattneub** [comment]
Also it may be of interest that the error is complaining about MacOSX10.13.sdk when I am using Mac OS X 10.12.

**Comment by mattneub** [comment]
Even more info. I installed Ruby 2.5.3 via rbenv, and switched to it; there, `sudo gem install rb-scpt` worked just fine. So the problem is confined, it seems, to the combination of Sierra, Xcode 9.2, and the built-in Ruby 2.3 belonging to Sierra.

**Comment by paul99** [comment]
A few semi-related comments re: installs on other macOS versions: in Oct '18 (before this thread), I tried to install on Mojave under built-in Ruby 2.3, and it failed similar to Matt's first comment above.

I used chruby/ruby-install with ruby-2.2.10, and rb-scpt gem installed & worked fine! (I later installed on a High-Sierra mac using same ruby.)

Yesterday, I upgraded my ruby to 2.6.2 on High Sierra, and rb-scpt gem installed and worked.

Since seeing this thread, I tried again installing the gem on the stock ruby 2.3 (High Sierra) and that installed fine also (I did not test that one). I am now on Xcode 10.1. (I have not had a chance to re-test that on Mojave)

Brendan, thanks so much for this port! It is super valuable and helpful to me, and I'm sure many others!! I looked for a tip-jar or ability to donate, I would happily buy you a few virtual beers for this one!

**Comment by mattneub** [comment]
Yeah, I agree with @paul99 - this is exactly why I put rb-appscript up, is so that someone with more ability than I have could modernize it and keep it alive. I'm really glad you did this, Brendan.

**Comment by BrendanThompson** [comment]
@paul99 @mattneub thanks both of you, I however certainly do not have more skill 😄 Ruby definitely not a strong point of mine, but happy to help when and where I can. 

---

@mattneub – are you still having issues on Sierra? Or, can we close this 🐶 off?

**Comment by mattneub** [comment]
Well it depends whether you care about not being able to install under the original conditions I initially reported. I'm perfectly happy with my workaround, which is to use rbenv and Ruby 2.5.3 - that works on Sierra and Mojave. But you might want to add a caution to the instructions in the readme.

**Comment by zenspider** [comment]
There are several stock ruby versions for OSX that have broken build setups and as such, extensions like this one will break. I think this is an issue for the readme more than something you should try to fix.

**Comment by zenspider** [comment]
I think this should be closed

**Comment by MattKitmanLabs** [comment]
This error is back!

**Comment by zenspider** [comment]
@MattKitmanLabs not helpful or informative. Please file a new issue.
